// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaBdap1BjftQiRdniZ5AQ6jkqcAfHu2SQ',
    appId: '1:130383918562:web:9cce14aecd9c35a1a8f5bb',
    messagingSenderId: '130383918562',
    projectId: 'brain-tumor-detector-6be52',
    authDomain: 'brain-tumor-detector-6be52.firebaseapp.com',
    storageBucket: 'brain-tumor-detector-6be52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsCZPmCAZW0FlKUGutd4X0yD2kiyI3Vcs',
    appId: '1:130383918562:android:f6ab7c7dcfdff998a8f5bb',
    messagingSenderId: '130383918562',
    projectId: 'brain-tumor-detector-6be52',
    storageBucket: 'brain-tumor-detector-6be52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfvbLN7tLX1WzzTPxGbAviKFCQKS-VdwQ',
    appId: '1:130383918562:ios:65bbc9fef682cdaea8f5bb',
    messagingSenderId: '130383918562',
    projectId: 'brain-tumor-detector-6be52',
    storageBucket: 'brain-tumor-detector-6be52.appspot.com',
    iosClientId: '130383918562-lsfh2nkv5eicm56pakjjun409a360mch.apps.googleusercontent.com',
    iosBundleId: 'com.redwolf.brainTumorDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfvbLN7tLX1WzzTPxGbAviKFCQKS-VdwQ',
    appId: '1:130383918562:ios:65bbc9fef682cdaea8f5bb',
    messagingSenderId: '130383918562',
    projectId: 'brain-tumor-detector-6be52',
    storageBucket: 'brain-tumor-detector-6be52.appspot.com',
    iosClientId: '130383918562-lsfh2nkv5eicm56pakjjun409a360mch.apps.googleusercontent.com',
    iosBundleId: 'com.redwolf.brainTumorDetector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaBdap1BjftQiRdniZ5AQ6jkqcAfHu2SQ',
    appId: '1:130383918562:web:2c5bf46dae899f28a8f5bb',
    messagingSenderId: '130383918562',
    projectId: 'brain-tumor-detector-6be52',
    authDomain: 'brain-tumor-detector-6be52.firebaseapp.com',
    storageBucket: 'brain-tumor-detector-6be52.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBaBdap1BjftQiRdniZ5AQ6jkqcAfHu2SQ',
    appId: '1:130383918562:web:947a4cf79ddc82f5a8f5bb',
    messagingSenderId: '130383918562',
    projectId: 'brain-tumor-detector-6be52',
    authDomain: 'brain-tumor-detector-6be52.firebaseapp.com',
    storageBucket: 'brain-tumor-detector-6be52.appspot.com',
  );
}
